version: '3'
services:
  mdb:
    image: psqlmoviesetup:latest
    networks: 
        - movienet
  dba:
    image: dpage/pgadmin4
    environment: 
        - PGADMIN_DEFAULT_EMAIL=t@t.com
        - PGADMIN_DEFAULT_PASSWORD=pass
    ports:
      - "5050:80"
    networks: 
        - movienet
networks: 
    movienet:
        driver: bridge