version: '3'
services:
  api:
    build: ./
    image: movieapi:latest
    ports:
      - "8080:8080"
      - "443:443"
    networks:
      -movienet
  mdb:
    build: ./docker-files/db
    image: psqlmoviesetup:latest
    networks: 
        - movienet
  dba:
    image: dpage/pgadmin4
    environment: 
        - PGADMIN_DEFAULT_EMAIL=t@t.com
        - PGADMIN_DEFAULT_PASSWORD=pass
    ports:
      - "5050:5050"
    networks: 
        - movienet
  redis:
    image: redis
    networks: 
      - movienet
  redisui:
    image: ediscommander/redis-commander:latest
    ports: 8081:8081
    environment: 
        - "REDIS_HOSTS=local:redis:6379"
    networks: 
        - movienet
networks: 
    movienet:
        driver: bridge